### ISSUE TITLE
How can I commit with Co-authoring type?

### ISSUE THREAD

**Issue by GodricGryffindorK** [netraxis/HTML_Scroll_Library#2]
Thanks for your help , @netraxis.
How to commit co-authors makes it easy to see who has contributed to every commit?

**Comment by netraxis** [comment]
To add co-authors to a commit, just add one or more “Co-authored-by” trailers to the end of the commit message:

````Commit message

Co-authored-by: Joel Califa <602352+califa@users.noreply.github.com>
Co-authored-by: Matt Clark <44023+mclark@users.noreply.github.com>````
